AUTH_SHEETY: "YOUR_HTTP_AUTH_STRING_FOR_SHEETY"
SHEETY_USER: "YOUR_SHEETY_SHEET_AUTH_USERNAME"
SHEETY_PASSWORD: "YOUR_SHEETY_SHEET_AUTH_PASSWORD"
KIWI_ENDPOINT: "https://api.tequila.kiwi.com/v2/search"
SHEETY_ENDPOINT_PRICES: "YOUR_SHEETY_SHEET_ENDPOINT_SAVING_THE_PRICES"
KIWI_API_KEY : "YOUR_KIWI_API_KEY"
HOMETOWN_IATA: "YOUR_HOMETOWN_IATA"
SHEETY_ENDPOINT_USERS: "YOUR_SHEETY_SHEET_ENDPOINT_SAVING_THE_USERS"